FROM openjdk:17
LABEL maintainer="Jakex01"
ENV PORT 8080
EXPOSE 8080
COPY ./target/defensive-programming-0.0.1-SNAPSHOT.jar defensive-programming-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/defensive-programming-0.0.1-SNAPSHOT.jar"]



