version: '3.1'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432:5432"
  bank:
    container_name: bank-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy